apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-lsfv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/happy-depl-ubxg-tenant/appstudio/dc-metro-map-lsfv@sha256:d48334b9bd02bf73d02bbb361cf451f506a629edbd1479c4d7f8559b00f73096
        name: my-nodejs
        resources: {}
status: {}
